gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - finger1_joint
     - finger2_joint
  gains:
      finger1_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      finger2_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
  constraints:
      goal_time: 3.0

      finger1_joint: {goal: 0.02}
      finger2_joint: {goal: 0.02}

  
  state_publish_rate:  50
  action_monitor_rate: 30
  stop_trajectory_duration: 0